spring.application.name = pfo
spring.main.banner-mode = off

logging.level.com.umtdg = INFO

spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/pfo
spring.datasource.username = pfo
spring.datasource.password = pfo

spring.jpa.hibernate.ddl-auto = update
